export const artworks = [
  {
    id: "1",
    title: "Abstract Harmony",
    artist: "Elena Rodriguez",
    description:
      "A vibrant exploration of color and form, this abstract piece invites viewers to interpret its dynamic composition through their own emotional lens. Layers of acrylic paint create depth and movement across the canvas.",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&h=800&fit=crop",
    price: 2800,
    year: 2023,
    dimensions: "36 × 48 in",
    medium: "Acrylic on canvas",
    category: "Paintings",
    location: "New York",
    availability: "Available",
  },
  {
    id: "2",
    title: "Urban Reflections",
    artist: "Marcus Chen",
    description:
      "This photographic series captures the interplay of light and architecture in modern cityscapes. Glass facades create mesmerizing reflections that transform familiar urban environments into abstract compositions.",
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=800&fit=crop",
    price: 1200,
    year: 2022,
    dimensions: "24 × 36 in",
    medium: "Digital photography, archival print",
    category: "Photography",
    location: "Chicago",
    availability: "Available",
  },
  {
    id: "3",
    title: "Eternal Form",
    artist: "Sophia Williams",
    description:
      "Carved from a single block of marble, this sculpture explores the relationship between negative space and solid form. Its smooth surfaces invite touch while its composition draws the eye around its continuous curves.",
    image: "https://images.unsplash.com/photo-1533158326339-7f3cf2404354?q=80&w=2268&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 5600,
    year: 2021,
    dimensions: "18 × 12 × 14 in",
    medium: "Marble",
    category: "Sculptures",
    location: "Los Angeles",
    availability: "Available",
  },
  {
    id: "4",
    title: "Digital Dreamscape",
    artist: "Aiden Park",
    description:
      "This digital artwork blends elements of surrealism and futurism to create an immersive landscape that exists between reality and imagination. Created using advanced 3D modeling and rendering techniques.",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&h=800&fit=crop",
    price: 1800,
    year: 2023,
    dimensions: "Variable (digital)",
    medium: "Digital art, NFT",
    category: "Digital",
    location: "Online Gallery",
    availability: "Available",
  },
  {
    id: "5",
    title: "Serenity in Blue",
    artist: "Isabella Johnson",
    description:
      "A contemplative seascape that captures the tranquil beauty of dawn over the ocean. Subtle gradations of blue create a sense of depth and atmosphere, inviting viewers into a moment of calm reflection.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=800&fit=crop",
    price: 3200,
    year: 2022,
    dimensions: "30 × 40 in",
    medium: "Oil on canvas",
    category: "Paintings",
    location: "San Francisco",
    availability: "Available",
  },
  {
    id: "6",
    title: "Fragmented Memory",
    artist: "David Kim",
    description:
      "This mixed media piece incorporates found objects, photographs, and paint to explore themes of memory and identity. Personal artifacts are transformed into a collective narrative about human experience.",
    image: "https://images.unsplash.com/photo-1579783901586-d88db74b4fe4?w=800&h=800&fit=crop",
    price: 2400,
    year: 2021,
    dimensions: "24 × 24 in",
    medium: "Mixed media on wood panel",
    category: "Paintings",
    location: "Boston",
    availability: "Available",
  },
  {
    id: "7",
    title: "Geometric Tension",
    artist: "Olivia Martinez",
    description:
      "A bold sculptural piece that plays with balance and weight. Steel elements create dynamic lines in space, challenging perceptions of stability and movement within a static form.",
    image: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800&h=800&fit=crop",
    price: 4800,
    year: 2023,
    dimensions: "36 × 24 × 18 in",
    medium: "Welded steel",
    category: "Sculptures",
    location: "Seattle",
    availability: "Available",
  },
  {
    id: "8",
    title: "Moment in Time",
    artist: "James Wilson",
    description:
      "This black and white photograph captures a fleeting urban moment, freezing the interaction between light, architecture, and human presence. The high contrast printing technique enhances the dramatic composition.",
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=800&fit=crop",
    price: 950,
    year: 2022,
    dimensions: "20 × 30 in",
    medium: "Silver gelatin print",
    category: "Photography",
    location: "New York",
    availability: "Available",
  },
  {
    id: "9",
    title: "Virtual Construct",
    artist: "Zoe Taylor",
    description:
      "An exploration of digital space and form, this generative artwork creates unique variations based on algorithmic parameters. The piece exists at the intersection of art, mathematics, and computer science.",
    image: "https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=800&h=800&fit=crop",
    price: 1600,
    year: 2023,
    dimensions: "Variable (digital)",
    medium: "Generative digital art",
    category: "Digital",
    location: "Online Gallery",
    availability: "Available",
  },
  {
    id: "10",
    title: "Organic Rhythm",
    artist: "Nathan Lee",
    description:
      "Inspired by natural patterns and growth structures, this ceramic sculpture embodies the harmony found in organic forms. The textured surface catches light and creates subtle shadows that change throughout the day.",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&h=800&fit=crop",
    price: 3800,
    year: 2021,
    dimensions: "22 × 18 × 16 in",
    medium: "Glazed ceramic",
    category: "Sculptures",
    location: "Portland",
    availability: "Available",
  },
  {
    id: "11",
    title: "Chromatic Journey",
    artist: "Elena Rodriguez",
    description:
      "A continuation of the artist's exploration of color relationships, this vibrant abstract painting creates a sense of movement and energy through bold brushwork and layered transparency.",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&h=800&fit=crop",
    price: 3100,
    year: 2023,
    dimensions: "40 × 36 in",
    medium: "Acrylic on canvas",
    category: "Paintings",
    location: "Miami",
    availability: "Available",
  },
  {
    id: "12",
    title: "Urban Solitude",
    artist: "Marcus Chen",
    description:
      "Part of the photographer's acclaimed urban series, this image captures the paradoxical isolation within crowded city environments. Architectural elements frame human figures in a narrative of modern existence.",
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=800&fit=crop",
    price: 1400,
    year: 2022,
    dimensions: "24 × 36 in",
    medium: "Digital photography, archival print",
    category: "Photography",
    location: "Chicago",
    availability: "Available",
  },
]

export const featuredArtworks = [
  {
    id: "1",
    title: "Abstract Harmony",
    artist: "Elena Rodriguez",
    description:
      "A vibrant exploration of color and form, this abstract piece invites viewers to interpret its dynamic composition through their own emotional lens. Layers of acrylic paint create depth and movement across the canvas.",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&h=800&fit=crop",
    price: 2800,
    category: "Paintings",
  },
  {
    id: "3",
    title: "Eternal Form",
    artist: "Sophia Williams",
    description:
      "Carved from a single block of marble, this sculpture explores the relationship between negative space and solid form. Its smooth surfaces invite touch while its composition draws the eye around its continuous curves.",
    image: "https://images.unsplash.com/photo-1565193566173-7a0b99d1e238?w=800&h=800&fit=crop",
    price: 5600,
    category: "Sculptures",
  },
  {
    id: "4",
    title: "Digital Dreamscape",
    artist: "Aiden Park",
    description:
      "This digital artwork blends elements of surrealism and futurism to create an immersive landscape that exists between reality and imagination. Created using advanced 3D modeling and rendering techniques.",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&h=800&fit=crop",
    price: 1800,
    category: "Digital",
  },
]

export const artists = [
  {
    id: "1",
    name: "Elena Rodriguez",
    specialty: "Painter",
    location: "New York, USA",
    image: "/placeholder.svg?height=600&width=600",
    biography:
      "Elena Rodriguez is known for her vibrant abstract compositions that explore the emotional resonance of color and form. Born in Madrid and educated in New York, her work bridges European and American artistic traditions.\n\nRodriguez's paintings have been exhibited in major galleries across North America and Europe. Her distinctive style combines bold brushwork with meticulous attention to the interaction of colors, creating dynamic visual experiences that invite personal interpretation.\n\nIn recent years, she has expanded her practice to include large-scale public art installations that bring her explorations of color into urban environments.",
    born: "1985, Madrid, Spain",
    nationality: "Spanish-American",
    education: "MFA, School of Visual Arts, New York",
    awards: "National Contemporary Art Prize (2020), Emerging Artist Grant (2018)",
    exhibitions: [
      {
        title: "Chromatic Dialogues: Solo Exhibition",
        year: "2023",
        location: "Whitney Museum, New York",
      },
      {
        title: "Abstract Visions",
        year: "2022",
        location: "Museum of Modern Art, Barcelona",
      },
      {
        title: "New Perspectives in Color",
        year: "2021",
        location: "Contemporary Arts Center, Chicago",
      },
      {
        title: "Emerging Voices",
        year: "2019",
        location: "Gallery of Modern Art, London",
      },
    ],
  },
  {
    id: "2",
    name: "Marcus Chen",
    specialty: "Photographer",
    location: "Chicago, USA",
    image: "/placeholder.svg?height=600&width=600",
    biography:
      "Marcus Chen's photography explores the intersection of urban architecture and human experience. His work captures fleeting moments within city environments, revealing unexpected beauty in everyday scenes.\n\nAfter beginning his career as an architectural photographer, Chen developed a distinctive style that combines technical precision with an empathetic eye for human stories. His images often play with reflection, light, and perspective to transform familiar cityscapes into contemplative visual narratives.\n\nChen's work has been published in numerous photography journals and exhibited internationally. He also leads workshops on urban photography and visual storytelling.",
    born: "1983, San Francisco, USA",
    nationality: "American",
    education: "BFA in Photography, Rhode Island School of Design",
    awards: "International Photography Award (2021), Urban Landscape Prize (2019)",
    exhibitions: [
      {
        title: "Urban Reflections: Solo Exhibition",
        year: "2023",
        location: "Museum of Contemporary Photography, Chicago",
      },
      {
        title: "City Rhythms",
        year: "2022",
        location: "International Center of Photography, New York",
      },
      {
        title: "Light and Shadow",
        year: "2020",
        location: "Gallery of Modern Photography, Tokyo",
      },
      {
        title: "American Perspectives",
        year: "2018",
        location: "National Portrait Gallery, Washington DC",
      },
    ],
  },
  {
    id: "3",
    name: "Sophia Williams",
    specialty: "Sculptor",
    location: "Los Angeles, USA",
    image: "/placeholder.svg?height=600&width=600",
    biography:
      "Sophia Williams creates sculptural works that explore the relationship between form, space, and material. Working primarily in marble and bronze, her pieces balance technical virtuosity with emotional resonance.\n\nWilliams' approach to sculpture is informed by classical traditions but expressed through contemporary sensibilities. Her work often addresses themes of permanence and transformation, with forms that seem to capture movement within solid materials.\n\nAfter completing her formal education in Florence, Williams established her studio in Los Angeles, where she continues to push the boundaries of sculptural practice while maintaining a deep respect for traditional craftsmanship.",
    born: "1979, Boston, USA",
    nationality: "American",
    education: "MFA in Sculpture, Florence Academy of Art",
    awards: "National Sculpture Society Award (2022), Pollock-Krasner Foundation Grant (2018)",
    exhibitions: [
      {
        title: "Form and Void: Solo Exhibition",
        year: "2023",
        location: "Getty Center, Los Angeles",
      },
      {
        title: "Contemporary Classics",
        year: "2022",
        location: "Museum of Fine Arts, Boston",
      },
      {
        title: "Material Transformations",
        year: "2020",
        location: "Sculpture Garden, San Francisco",
      },
      {
        title: "New Directions in Form",
        year: "2018",
        location: "Biennale di Scultura, Venice",
      },
    ],
  },
  {
    id: "4",
    name: "Aiden Park",
    specialty: "Digital Artist",
    location: "Seoul, South Korea",
    image: "/placeholder.svg?height=600&width=600",
    biography:
      "Aiden Park works at the intersection of art and technology, creating immersive digital experiences that challenge perceptions of reality and virtuality. His practice spans 3D modeling, animation, and interactive installations.\n\nPark's work explores themes of digital identity, artificial intelligence, and the evolving relationship between humans and technology. His visually stunning pieces often incorporate elements of both Eastern and Western aesthetic traditions, reimagined through contemporary digital tools.\n\nEducated in both computer science and fine arts, Park brings technical expertise and artistic vision to his pioneering work in the digital realm. He has collaborated with technology companies and cultural institutions to create groundbreaking digital art experiences.",
    born: "1990, Seoul, South Korea",
    nationality: "South Korean",
    education: "MFA in Digital Arts, Rhode Island School of Design; BS in Computer Science, KAIST",
    awards: "Lumen Prize for Digital Art (2022), Asia Digital Art Award (2020)",
    exhibitions: [
      {
        title: "Virtual Horizons: Solo Exhibition",
        year: "2023",
        location: "ZKM Center for Art and Media, Karlsruhe",
      },
      {
        title: "Digital Realities",
        year: "2022",
        location: "Ars Electronica, Linz",
      },
      {
        title: "Future Visions",
        year: "2021",
        location: "National Museum of Modern and Contemporary Art, Seoul",
      },
      {
        title: "Art in the Age of AI",
        year: "2019",
        location: "Victoria and Albert Museum, London",
      },
    ],
  },
  {
    id: "5",
    name: "Isabella Johnson",
    specialty: "Painter",
    location: "San Francisco, USA",
    image: "/placeholder.svg?height=600&width=600",
    biography:
      "Isabella Johnson's oil paintings are characterized by their luminous quality and atmospheric depth. Specializing in landscapes and seascapes, her work captures fleeting moments of natural beauty with remarkable sensitivity.\n\nJohnson's technique draws from classical traditions of oil painting while incorporating contemporary approaches to color and composition. Her work often explores the emotional and psychological dimensions of natural environments, inviting viewers into contemplative engagement with the depicted scenes.\n\nBased in San Francisco, Johnson finds inspiration in the diverse landscapes of California, from coastal vistas to mountain ranges. Her studio practice involves both plein air studies and larger studio compositions developed from these direct observations.",
    born: "1982, Portland, USA",
    nationality: "American",
    education: "BFA in Painting, California College of the Arts",
    awards: "American Art Prize (2021), Landscape Painting Award (2019)",
    exhibitions: [
      {
        title: "Luminous Horizons: Solo Exhibition",
        year: "2023",
        location: "de Young Museum, San Francisco",
      },
      {
        title: "Contemporary Landscapes",
        year: "2022",
        location: "Portland Art Museum",
      },
      {
        title: "American Vistas",
        year: "2020",
        location: "National Gallery, Washington DC",
      },
      {
        title: "New Naturalism",
        year: "2018",
        location: "Gallery of California Art, Oakland",
      },
    ],
  },
  {
    id: "6",
    name: "David Kim",
    specialty: "Mixed Media Artist",
    location: "Boston, USA",
    image: "/placeholder.svg?height=600&width=600",
    biography:
      "David Kim creates complex mixed media works that explore themes of memory, identity, and cultural heritage. His distinctive approach combines traditional painting techniques with collage, found objects, and digital elements.\n\nKim's art often draws from his personal experience as a Korean-American, examining the intersection of different cultural influences and the construction of identity across generations. His work has been recognized for its emotional depth and innovative formal qualities.\n\nAfter studying both Eastern and Western artistic traditions, Kim developed a unique visual language that bridges diverse cultural references. His studio practice involves collecting and transforming materials that carry personal or cultural significance.",
    born: "1988, Boston, USA",
    nationality: "Korean-American",
    education: "MFA in Fine Arts, Yale University",
    awards: "Guggenheim Fellowship (2022), Joan Mitchell Foundation Grant (2019)",
    exhibitions: [
      {
        title: "Fragments and Memories: Solo Exhibition",
        year: "2023",
        location: "Institute of Contemporary Art, Boston",
      },
      {
        title: "Identity in Flux",
        year: "2022",
        location: "Museum of Contemporary Art, Los Angeles",
      },
      {
        title: "Diaspora Narratives",
        year: "2021",
        location: "Asia Society, New York",
      },
      {
        title: "New American Voices",
        year: "2019",
        location: "Whitney Museum, New York",
      },
    ],
  },
  {
    id: "7",
    name: "Olivia Martinez",
    specialty: "Sculptor",
    location: "Seattle, USA",
    image: "/placeholder.svg?height=600&width=600",
    biography:
      "Olivia Martinez creates bold sculptural works that explore the dynamic relationship between form, space, and material. Working primarily with metal, her pieces often feature dramatic lines and precarious balances that challenge perceptions of weight and stability.\n\nMartinez's approach to sculpture is informed by her background in engineering and her interest in the physical properties of materials. Her work investigates themes of tension, equilibrium, and the intersection of natural and industrial forms.\n\nBased in Seattle, Martinez has developed innovative techniques for working with steel and other metals. Her large-scale public installations can be found in urban spaces across the United States, where they create striking dialogues with their architectural surroundings.",
    born: "1984, Mexico City, Mexico",
    nationality: "Mexican-American",
    education: "MFA in Sculpture, Rhode Island School of Design; BS in Mechanical Engineering, MIT",
    awards: "Public Art Network Award (2022), Sculpture Space Fellowship (2019)",
    exhibitions: [
      {
        title: "Forces in Balance: Solo Exhibition",
        year: "2023",
        location: "Seattle Art Museum",
      },
      {
        title: "Metal and Motion",
        year: "2022",
        location: "Museum of Contemporary Craft, Portland",
      },
      {
        title: "Structural Innovations",
        year: "2020",
        location: "Sculpture Center, New York",
      },
      {
        title: "Women in Sculpture",
        year: "2018",
        location: "National Museum of Women in the Arts, Washington DC",
      },
    ],
  },
  {
    id: "8",
    name: "James Wilson",
    specialty: "Photographer",
    location: "New York, USA",
    image: "/placeholder.svg?height=600&width=600",
    biography:
      "James Wilson is renowned for his black and white photography that captures the poetic dimensions of urban life. His work combines documentary precision with artistic sensibility, revealing intimate moments within public spaces.\n\nWilson's photographic practice is characterized by patient observation and an intuitive sense of timing. Working primarily with traditional film cameras and silver gelatin printing processes, he maintains a connection to the craft's historical roots while addressing contemporary themes.\n\nBased in New York City, Wilson finds endless inspiration in the city's diverse neighborhoods and inhabitants. His images have been widely published and exhibited, earning recognition for their distinctive visual style and emotional resonance.",
    born: "1975, London, UK",
    nationality: "British-American",
    education: "MA in Photography, School of Visual Arts, New York",
    awards: "Leica Oskar Barnack Award (2021), ICP Infinity Award (2018)",
    exhibitions: [
      {
        title: "Street Poetry: Solo Exhibition",
        year: "2023",
        location: "International Center of Photography, New York",
      },
      {
        title: "Urban Narratives",
        year: "2022",
        location: "Tate Modern, London",
      },
      {
        title: "The Decisive Moment",
        year: "2020",
        location: "Aperture Foundation, New York",
      },
      {
        title: "Black and White in America",
        year: "2018",
        location: "Museum of the City of New York",
      },
    ],
  },
]

export const exhibitions = [
  {
    id: "1",
    title: "Perspectives: New Horizons in Contemporary Art",
    subtitle: "An exploration of emerging voices in the global art scene",
    description:
      "This exhibition brings together works by fifteen artists from around the world who are pushing the boundaries of contemporary art practice. Through diverse media including painting, sculpture, photography, and digital art, these artists offer fresh perspectives on current social, political, and environmental issues.\n\nThe exhibition is organized around three thematic sections: 'Reimagining Identity,' 'Environmental Dialogues,' and 'Digital Futures.' Each section presents works that engage with these themes through innovative formal approaches and conceptual frameworks.\n\n'Perspectives' aims to highlight voices that are shaping the future direction of contemporary art while fostering dialogue about the role of art in addressing the complex challenges of our time.",
    curatorNote:
      "In curating 'Perspectives,' I sought to bring together artists whose work not only demonstrates technical excellence but also offers meaningful engagement with the pressing questions of our era. The selected artists represent diverse backgrounds and approaches, yet their works resonate with each other in surprising and illuminating ways.\n\nThe exhibition invites viewers to consider how contemporary art can help us see familiar issues from new angles, challenging assumptions and opening spaces for fresh thinking. In a time of rapid change and uncertainty, these artists remind us of art's unique capacity to envision alternative possibilities and inspire transformative dialogue.\n\n- Dr. Sarah Chen, Chief Curator",
    image: "/placeholder.svg?height=1080&width=1920",
    dateRange: "June 15 - August 30, 2025",
    startDate: "2025-06-15",
    endDate: "2025-08-30",
    status: "upcoming",
    location: "Main Gallery",
    address: "123 Gallery Street, New York, NY 10001",
    hours: "Tuesday - Sunday, 10:00 AM - 6:00 PM",
    admission: "General: $15 | Students & Seniors: $10 | Members: Free",
    artworkIds: ["1", "3", "4", "7", "9", "11"],
  },
  {
    id: "2",
    title: "Urban Narratives: The City in Contemporary Photography",
    subtitle: "Exploring the complex relationship between people and urban environments",
    description:
      "This exhibition examines how contemporary photographers capture and interpret urban life across different cities and cultures. Featuring works by twelve photographers, 'Urban Narratives' presents diverse perspectives on the modern city as a site of both connection and alienation, opportunity and inequality.\n\nThe selected photographs document architectural transformations, street life, and intimate moments within public spaces, revealing the complex social fabric of urban environments. From densely populated metropolises to changing industrial landscapes, these images invite viewers to reconsider their relationship with the built environment and the communities that inhabit it.\n\nThrough various photographic approaches—from documentary to conceptual—the exhibition highlights how the medium continues to evolve while maintaining its power to record, critique, and reimagine urban experience.",
    curatorNote:
      "Photography has been inextricably linked with urban life since both the medium and the modern city emerged in the 19th century. This exhibition explores how contemporary photographers are extending and reimagining this relationship in the 21st century.\n\nThe photographers featured in 'Urban Narratives' move beyond mere documentation to create works that function as visual poetry, social commentary, and personal reflection. Their images reveal the city not as a static backdrop but as a dynamic entity shaped by human activity and, in turn, shaping human experience.\n\nIn selecting works for this exhibition, I was particularly interested in photographers who find unexpected beauty in ordinary urban scenes and who capture the ephemeral moments that might otherwise go unnoticed in the rush of city life.\n\n- Michael Torres, Photography Curator",
    image: "/placeholder.svg?height=1080&width=1920",
    dateRange: "March 10 - May 25, 2025",
    startDate: "2025-03-10",
    endDate: "2025-05-25",
    status: "upcoming",
    location: "Photography Gallery",
    address: "123 Gallery Street, New York, NY 10001",
    hours: "Tuesday - Sunday, 10:00 AM - 6:00 PM",
    admission: "General: $12 | Students & Seniors: $8 | Members: Free",
    artworkIds: ["2", "8", "12"],
  },
  {
    id: "3",
    title: "Color Theory: Abstract Painting Now",
    subtitle: "Contemporary approaches to color, form, and composition",
    description:
      "This exhibition celebrates the enduring vitality of abstract painting in contemporary art. Bringing together works by established and emerging artists, 'Color Theory' explores how painters are extending the language of abstraction through innovative approaches to color, form, and composition.\n\nThe exhibition highlights the diverse ways contemporary artists engage with the legacy of abstract painting while addressing current aesthetic, conceptual, and social concerns. From geometric precision to gestural expression, from subtle chromatic harmonies to bold color contrasts, the works on display demonstrate the rich possibilities of non-representational painting today.\n\nFeaturing both large-scale canvases and intimate works on paper, the exhibition invites viewers to experience the physical and emotional impact of abstract art while considering its continued relevance in contemporary culture.",
    curatorNote:
      "Abstract painting has been declared 'dead' numerous times throughout art history, yet it continues to evolve and find new expressions in each generation of artists. This exhibition demonstrates the medium's remarkable resilience and adaptability.\n\nThe artists featured in 'Color Theory' are not simply revisiting historical styles but are actively reimagining what abstract painting can be in the 21st century. They bring fresh perspectives informed by digital culture, global artistic traditions, and contemporary social concerns while maintaining deep engagement with the fundamental elements of painting: color, form, and surface.\n\nIn organizing this exhibition, I wanted to show how abstract painting remains a vital means of expression, capable of conveying complex emotions and ideas that resist verbal articulation.\n\n- Dr. Elena Vasquez, Contemporary Art Curator",
    image: "/placeholder.svg?height=1080&width=1920",
    dateRange: "January 15 - April 8, 2025",
    startDate: "2025-01-15",
    endDate: "2025-04-08",
    status: "current",
    location: "Contemporary Gallery",
    address: "123 Gallery Street, New York, NY 10001",
    hours: "Tuesday - Sunday, 10:00 AM - 6:00 PM",
    admission: "General: $15 | Students & Seniors: $10 | Members: Free",
    artworkIds: ["1", "5", "6", "11"],
  },
  {
    id: "4",
    title: "Material Transformations: Contemporary Sculpture",
    subtitle: "Exploring new directions in three-dimensional art",
    description:
      "This exhibition showcases the innovative ways contemporary sculptors are working with traditional and new materials to create compelling three-dimensional experiences. From marble and bronze to recycled plastics and digital fabrication, the featured artists demonstrate the expanded possibilities of sculptural practice today.\n\nThe works on display range from intimate objects to large-scale installations, each exploring different aspects of materiality, form, and space. The exhibition examines how contemporary sculptors are addressing environmental concerns, technological advancement, and social issues through their choice and manipulation of materials.\n\n'Material Transformations' invites viewers to consider sculpture not just as static objects but as dynamic investigations into the relationship between material, meaning, and human experience.",
    curatorNote:
      "Sculpture has always been fundamentally concerned with the transformation of raw materials into meaningful forms. In our current moment of environmental crisis and technological revolution, sculptors are finding new urgency in questions about materiality and making.\n\nThe artists in this exhibition approach materials with both reverence and innovation, honoring traditional craft knowledge while embracing new possibilities offered by contemporary tools and techniques. Their works challenge us to reconsider our relationship with the physical world and the objects that surround us.\n\nThis exhibition celebrates sculpture's unique capacity to engage our bodies and senses while addressing some of the most pressing concerns of our time.\n\n- James Morrison, Sculpture Curator",
    image: "/placeholder.svg?height=1080&width=1920",
    dateRange: "September 12 - December 15, 2024",
    startDate: "2024-09-12",
    endDate: "2024-12-15",
    status: "past",
    location: "Sculpture Hall",
    address: "123 Gallery Street, New York, NY 10001",
    hours: "Tuesday - Sunday, 10:00 AM - 6:00 PM",
    admission: "General: $15 | Students & Seniors: $10 | Members: Free",
    artworkIds: ["3", "7", "10"],
  },
  {
    id: "5",
    title: "Digital Frontiers: Art in the Age of AI",
    subtitle: "Exploring the intersection of art and artificial intelligence",
    description:
      "This groundbreaking exhibition examines how artists are engaging with artificial intelligence and machine learning technologies to create new forms of artistic expression. Featuring interactive installations, generative artworks, and AI-assisted creations, 'Digital Frontiers' explores both the creative possibilities and ethical implications of these emerging technologies.\n\nThe exhibition presents works that range from collaborative human-AI projects to fully autonomous generative systems. Artists explore themes of creativity, authorship, and the nature of intelligence while pushing the boundaries of what art can be in the digital age.\n\n'Digital Frontiers' invites visitors to experience firsthand how artificial intelligence is transforming artistic practice and to consider the broader implications of these technologies for creativity and human expression.",
    curatorNote:
      "As artificial intelligence becomes increasingly sophisticated, artists are among the first to explore its creative potential while also questioning its implications for human creativity and agency. This exhibition brings together artists who are working at the cutting edge of this technological frontier.\n\nThe works in 'Digital Frontiers' demonstrate that AI is not replacing human creativity but rather opening new avenues for artistic exploration. These artists are using AI as a collaborator, a tool, and sometimes as a subject of investigation, creating works that would be impossible without these technologies.\n\nThis exhibition aims to foster dialogue about the role of AI in creative practice and its broader impact on society and culture.\n\n- Dr. Alex Chen, Digital Arts Curator",
    image: "/placeholder.svg?height=1080&width=1920",
    dateRange: "October 20, 2024 - February 10, 2025",
    startDate: "2024-10-20",
    endDate: "2025-02-10",
    status: "current",
    location: "Digital Arts Space",
    address: "123 Gallery Street, New York, NY 10001",
    hours: "Tuesday - Sunday, 10:00 AM - 6:00 PM",
    admission: "General: $18 | Students & Seniors: $12 | Members: Free",
    artworkIds: ["4", "9"],
  },
]

export const teamMembers = [
  {
    id: "1",
    name: "Dr. Sarah Chen",
    position: "Chief Curator",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "2",
    name: "Michael Torres",
    position: "Photography Curator",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "3",
    name: "Dr. Elena Vasquez",
    position: "Contemporary Art Curator",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "4",
    name: "James Morrison",
    position: "Sculpture Curator",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "5",
    name: "Dr. Alex Chen",
    position: "Digital Arts Curator",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "6",
    name: "Maria Rodriguez",
    position: "Gallery Director",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "7",
    name: "David Park",
    position: "Education Coordinator",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "8",
    name: "Lisa Thompson",
    position: "Collections Manager",
    image: "/placeholder.svg?height=400&width=400",
  },
]
