export const artworks = [
  {
    id: "1",
    title: "Abstract Harmony",
    artist: "Elena Rodriguez",
    description:
      "A vibrant exploration of color and form, this abstract piece invites viewers to interpret its dynamic composition through their own emotional lens. Layers of acrylic paint create depth and movement across the canvas.",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&h=800&fit=crop",
    price: 2800,
    year: 2023,
    dimensions: "36 × 48 in",
    medium: "Acrylic on canvas",
    category: "Paintings",
    location: "New York",
    availability: "Available",
  },
  {
    id: "2",
    title: "Urban Reflections",
    artist: "Marcus Chen",
    description:
      "This photographic series captures the interplay of light and architecture in modern cityscapes. Glass facades create mesmerizing reflections that transform familiar urban environments into abstract compositions.",
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=800&fit=crop",
    price: 1200,
    year: 2022,
    dimensions: "24 × 36 in",
    medium: "Digital photography, archival print",
    category: "Photography",
    location: "Chicago",
    availability: "Available",
  },
  {
    id: "3",
    title: "Eternal Form",
    artist: "Sophia Williams",
    description:
      "Carved from a single block of marble, this sculpture explores the relationship between negative space and solid form. Its smooth surfaces invite touch while its composition draws the eye around its continuous curves.",
    image: "https://images.unsplash.com/photo-1533158326339-7f3cf2404354?w=800&h=800&fit=crop",
    price: 5600,
    year: 2021,
    dimensions: "18 × 12 × 14 in",
    medium: "Marble",
    category: "Sculptures",
    location: "Los Angeles",
    availability: "Available",
  },
  {
    id: "4",
    title: "Digital Dreamscape",
    artist: "Aiden Park",
    description:
      "This digital artwork blends elements of surrealism and futurism to create an immersive landscape that exists between reality and imagination. Created using advanced 3D modeling and rendering techniques.",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&h=800&fit=crop",
    price: 1800,
    year: 2023,
    dimensions: "Variable (digital)",
    medium: "Digital art, NFT",
    category: "Digital",
    location: "Online Gallery",
    availability: "Available",
  },
  {
    id: "5",
    title: "Serenity in Blue",
    artist: "Isabella Johnson",
    description:
      "A contemplative seascape that captures the tranquil beauty of dawn over the ocean. Subtle gradations of blue create a sense of depth and atmosphere, inviting viewers into a moment of calm reflection.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=800&fit=crop",
    price: 3200,
    year: 2022,
    dimensions: "30 × 40 in",
    medium: "Oil on canvas",
    category: "Paintings",
    location: "San Francisco",
    availability: "Available",
  },
  {
    id: "6",
    title: "Fragmented Memory",
    artist: "David Kim",
    description:
      "This mixed media piece incorporates found objects, photographs, and paint to explore themes of memory and identity. Personal artifacts are transformed into a collective narrative about human experience.",
    image: "https://images.unsplash.com/photo-1579783901586-d88db74b4fe4?w=800&h=800&fit=crop",
    price: 2400,
    year: 2021,
    dimensions: "24 × 24 in",
    medium: "Mixed media on wood panel",
    category: "Paintings",
    location: "Boston",
    availability: "Available",
  },
  {
    id: "7",
    title: "Geometric Tension",
    artist: "Olivia Martinez",
    description:
      "A bold sculptural piece that plays with balance and weight. Steel elements create dynamic lines in space, challenging perceptions of stability and movement within a static form.",
    image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=800&h=800&fit=crop",
    price: 4800,
    year: 2023,
    dimensions: "36 × 24 × 18 in",
    medium: "Welded steel",
    category: "Sculptures",
    location: "Seattle",
    availability: "Available",
  },
  {
    id: "8",
    title: "Moment in Time",
    artist: "James Wilson",
    description:
      "This black and white photograph captures a fleeting urban moment, freezing the interaction between light, architecture, and human presence. The high contrast printing technique enhances the dramatic composition.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=800&h=800&fit=crop",
    price: 950,
    year: 2022,
    dimensions: "20 × 30 in",
    medium: "Silver gelatin print",
    category: "Photography",
    location: "New York",
    availability: "Available",
  },
  {
    id: "9",
    title: "Virtual Construct",
    artist: "Zoe Taylor",
    description:
      "An exploration of digital space and form, this generative artwork creates unique variations based on algorithmic parameters. The piece exists at the intersection of art, mathematics, and computer science.",
    image: "https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=800&h=800&fit=crop",
    price: 1600,
    year: 2023,
    dimensions: "Variable (digital)",
    medium: "Generative digital art",
    category: "Digital",
    location: "Online Gallery",
    availability: "Available",
  },
  {
    id: "10",
    title: "Organic Rhythm",
    artist: "Nathan Lee",
    description:
      "Inspired by natural patterns and growth structures, this ceramic sculpture embodies the harmony found in organic forms. The textured surface catches light and creates subtle shadows that change throughout the day.",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&h=800&fit=crop",
    price: 3800,
    year: 2021,
    dimensions: "22 × 18 × 16 in",
    medium: "Glazed ceramic",
    category: "Sculptures",
    location: "Portland",
    availability: "Available",
  },
  {
    id: "11",
    title: "Chromatic Journey",
    artist: "Elena Rodriguez",
    description:
      "A continuation of the artist's exploration of color relationships, this vibrant abstract painting creates a sense of movement and energy through bold brushwork and layered transparency.",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&h=800&fit=crop",
    price: 3100,
    year: 2023,
    dimensions: "40 × 36 in",
    medium: "Acrylic on canvas",
    category: "Paintings",
    location: "Miami",
    availability: "Available",
  },
  {
    id: "12",
    title: "Urban Solitude",
    artist: "Marcus Chen",
    description:
      "Part of the photographer's acclaimed urban series, this image captures the paradoxical isolation within crowded city environments. Architectural elements frame human figures in a narrative of modern existence.",
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=800&fit=crop",
    price: 1400,
    year: 2022,
    dimensions: "24 × 36 in",
    medium: "Digital photography, archival print",
    category: "Photography",
    location: "Chicago",
    availability: "Available",
  },
]

export const featuredArtworks = [
  {
    id: "1",
    title: "Abstract Harmony",
    artist: "Elena Rodriguez",
    description:
      "A vibrant exploration of color and form, this abstract piece invites viewers to interpret its dynamic composition through their own emotional lens. Layers of acrylic paint create depth and movement across the canvas.",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&h=800&fit=crop",
    price: 2800,
    category: "Paintings",
  },
  {
    id: "3",
    title: "Eternal Form",
    artist: "Sophia Williams",
    description:
      "Carved from a single block of marble, this sculpture explores the relationship between negative space and solid form. Its smooth surfaces invite touch while its composition draws the eye around its continuous curves.",
    image: "https://images.unsplash.com/photo-1533158326339-7f3cf2404354?w=800&h=800&fit=crop",
    price: 5600,
    category: "Sculptures",
  },
  {
    id: "4",
    title: "Digital Dreamscape",
    artist: "Aiden Park",
    description:
      "This digital artwork blends elements of surrealism and futurism to create an immersive landscape that exists between reality and imagination. Created using advanced 3D modeling and rendering techniques.",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&h=800&fit=crop",
    price: 1800,
    category: "Digital",
  },
]

export const artists = [
  {
    id: "1",
    name: "Elena Rodriguez",
    specialty: "Painter",
    location: "New York, USA",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=800&fit=crop",
    socialMedia: {
      instagram: "https://instagram.com/elena.rodriguez.art",
      twitter: "https://twitter.com/elenarodriguez",
      website: "https://elenarodriguez.art",
    },
    biography:
      "Elena Rodriguez is known for her vibrant abstract compositions that explore the emotional resonance of color and form. Born in Madrid and educated in New York, her work bridges European and American artistic traditions.\n\nRodriguez's paintings have been exhibited in major galleries across North America and Europe. Her distinctive style combines bold brushwork with meticulous attention to the interaction of colors, creating dynamic visual experiences that invite personal interpretation.\n\nIn recent years, she has expanded her practice to include large-scale public art installations that bring her explorations of color into urban environments.",
    born: "1985, Madrid, Spain",
    nationality: "Spanish-American",
    education: "MFA, School of Visual Arts, New York",
    awards: "National Contemporary Art Prize (2020), Emerging Artist Grant (2018)",
    exhibitions: [
      {
        title: "Chromatic Dialogues: Solo Exhibition",
        year: "2023",
        location: "Whitney Museum, New York",
      },
      {
        title: "Abstract Visions",
        year: "2022",
        location: "Museum of Modern Art, Barcelona",
      },
      {
        title: "New Perspectives in Color",
        year: "2021",
        location: "Contemporary Arts Center, Chicago",
      },
      {
        title: "Emerging Voices",
        year: "2019",
        location: "Gallery of Modern Art, London",
      },
    ],
  },
  {
    id: "2",
    name: "Marcus Chen",
    specialty: "Photographer",
    location: "Chicago, USA",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop",
    socialMedia: {
      instagram: "https://instagram.com/marcus.chen.photo",
      twitter: "https://twitter.com/marcuschen",
      website: "https://marcuschen.photo",
    },
    biography:
      "Marcus Chen's photography explores the intersection of urban architecture and human experience. His work captures fleeting moments within city environments, revealing unexpected beauty in everyday scenes.\n\nAfter beginning his career as an architectural photographer, Chen developed a distinctive style that combines technical precision with an empathetic eye for human stories. His images often play with reflection, light, and perspective to transform familiar cityscapes into contemplative visual narratives.\n\nChen's work has been published in numerous photography journals and exhibited internationally. He also leads workshops on urban photography and visual storytelling.",
    born: "1983, San Francisco, USA",
    nationality: "American",
    education: "BFA in Photography, Rhode Island School of Design",
    awards: "International Photography Award (2021), Urban Landscape Prize (2019)",
    exhibitions: [
      {
        title: "Urban Reflections: Solo Exhibition",
        year: "2023",
        location: "Museum of Contemporary Photography, Chicago",
      },
      {
        title: "City Rhythms",
        year: "2022",
        location: "International Center of Photography, New York",
      },
      {
        title: "Light and Shadow",
        year: "2020",
        location: "Gallery of Modern Photography, Tokyo",
      },
      {
        title: "American Perspectives",
        year: "2018",
        location: "National Portrait Gallery, Washington DC",
      },
    ],
  },
  {
    id: "3",
    name: "Sophia Williams",
    specialty: "Sculptor",
    location: "Los Angeles, USA",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&h=800&fit=crop",
    socialMedia: {
      instagram: "https://instagram.com/sophia.williams.sculpture",
      twitter: "https://twitter.com/sophiawilliams",
      website: "https://sophiawilliams.art",
    },
    biography:
      "Sophia Williams creates sculptural works that explore the relationship between form, space, and material. Working primarily in marble and bronze, her pieces balance technical virtuosity with emotional resonance.\n\nWilliams' approach to sculpture is informed by classical traditions but expressed through contemporary sensibilities. Her work often addresses themes of permanence and transformation, with forms that seem to capture movement within solid materials.\n\nAfter completing her formal education in Florence, Williams established her studio in Los Angeles, where she continues to push the boundaries of sculptural practice while maintaining a deep respect for traditional craftsmanship.",
    born: "1979, Boston, USA",
    nationality: "American",
    education: "MFA in Sculpture, Florence Academy of Art",
    awards: "National Sculpture Society Award (2022), Pollock-Krasner Foundation Grant (2018)",
    exhibitions: [
      {
        title: "Form and Void: Solo Exhibition",
        year: "2023",
        location: "Getty Center, Los Angeles",
      },
      {
        title: "Contemporary Classics",
        year: "2022",
        location: "Museum of Fine Arts, Boston",
      },
      {
        title: "Material Transformations",
        year: "2020",
        location: "Sculpture Garden, San Francisco",
      },
      {
        title: "New Directions in Form",
        year: "2018",
        location: "Biennale di Scultura, Venice",
      },
    ],
  },
  {
    id: "4",
    name: "Aiden Park",
    specialty: "Digital Artist",
    location: "Seoul, South Korea",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=800&fit=crop",
    socialMedia: {
      instagram: "https://instagram.com/aiden.park.digital",
      twitter: "https://twitter.com/aidenpark",
      website: "https://aidenpark.digital",
    },
    biography:
      "Aiden Park works at the intersection of art and technology, creating immersive digital experiences that challenge perceptions of reality and virtuality. His practice spans 3D modeling, animation, and interactive installations.\n\nPark's work explores themes of digital identity, artificial intelligence, and the evolving relationship between humans and technology. His visually stunning pieces often incorporate elements of both Eastern and Western aesthetic traditions, reimagined through contemporary digital tools.\n\nEducated in both computer science and fine arts, Park brings technical expertise and artistic vision to his pioneering work in the digital realm. He has collaborated with technology companies and cultural institutions to create groundbreaking digital art experiences.",
    born: "1990, Seoul, South Korea",
    nationality: "South Korean",
    education: "MFA in Digital Arts, Rhode Island School of Design; BS in Computer Science, KAIST",
    awards: "Lumen Prize for Digital Art (2022), Asia Digital Art Award (2020)",
    exhibitions: [
      {
        title: "Virtual Horizons: Solo Exhibition",
        year: "2023",
        location: "ZKM Center for Art and Media, Karlsruhe",
      },
      {
        title: "Digital Realities",
        year: "2022",
        location: "Ars Electronica, Linz",
      },
      {
        title: "Future Visions",
        year: "2021",
        location: "National Museum of Modern and Contemporary Art, Seoul",
      },
      {
        title: "Art in the Age of AI",
        year: "2019",
        location: "Victoria and Albert Museum, London",
      },
    ],
  },
  {
    id: "5",
    name: "Isabella Johnson",
    specialty: "Painter",
    location: "San Francisco, USA",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=800&fit=crop",
    socialMedia: {
      instagram: "https://instagram.com/isabella.johnson.art",
      twitter: "https://twitter.com/isabellajohnson",
      website: "https://isabellajohnson.art",
    },
    biography:
      "Isabella Johnson's oil paintings are characterized by their luminous quality and atmospheric depth. Specializing in landscapes and seascapes, her work captures fleeting moments of natural beauty with remarkable sensitivity.\n\nJohnson's technique draws from classical traditions of oil painting while incorporating contemporary approaches to color and composition. Her work often explores the emotional and psychological dimensions of natural environments, inviting viewers into contemplative engagement with the depicted scenes.\n\nBased in San Francisco, Johnson finds inspiration in the diverse landscapes of California, from coastal vistas to mountain ranges. Her studio practice involves both plein air studies and larger studio compositions developed from these direct observations.",
    born: "1982, Portland, USA",
    nationality: "American",
    education: "BFA in Painting, California College of the Arts",
    awards: "American Art Prize (2021), Landscape Painting Award (2019)",
    exhibitions: [
      {
        title: "Luminous Horizons: Solo Exhibition",
        year: "2023",
        location: "de Young Museum, San Francisco",
      },
      {
        title: "Contemporary Landscapes",
        year: "2022",
        location: "Portland Art Museum",
      },
      {
        title: "American Vistas",
        year: "2020",
        location: "National Gallery, Washington DC",
      },
      {
        title: "New Naturalism",
        year: "2018",
        location: "Gallery of California Art, Oakland",
      },
    ],
  },
  {
    id: "6",
    name: "David Kim",
    specialty: "Mixed Media Artist",
    location: "Boston, USA",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=800&fit=crop",
    socialMedia: {
      instagram: "https://instagram.com/david.kim.art",
      twitter: "https://twitter.com/davidkim",
      website: "https://davidkim.art",
    },
    biography:
      "David Kim creates complex mixed media works that explore themes of memory, identity, and cultural heritage. His distinctive approach combines traditional painting techniques with collage, found objects, and digital elements.\n\nKim's art often draws from his personal experience as a Korean-American, examining the intersection of different cultural influences and the construction of identity across generations. His work has been recognized for its emotional depth and innovative formal qualities.\n\nAfter studying both Eastern and Western artistic traditions, Kim developed a unique visual language that bridges diverse cultural references. His studio practice involves collecting and transforming materials that carry personal or cultural significance.",
    born: "1988, Boston, USA",
    nationality: "Korean-American",
    education: "MFA in Fine Arts, Yale University",
    awards: "Guggenheim Fellowship (2022), Joan Mitchell Foundation Grant (2019)",
    exhibitions: [
      {
        title: "Fragments and Memories: Solo Exhibition",
        year: "2023",
        location: "Institute of Contemporary Art, Boston",
      },
      {
        title: "Identity in Flux",
        year: "2022",
        location: "Museum of Contemporary Art, Los Angeles",
      },
      {
        title: "Diaspora Narratives",
        year: "2021",
        location: "Asia Society, New York",
      },
      {
        title: "New American Voices",
        year: "2019",
        location: "Whitney Museum, New York",
      },
    ],
  },
  {
    id: "7",
    name: "Olivia Martinez",
    specialty: "Sculptor",
    location: "Seattle, USA",
    image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=800&h=800&fit=crop",
    socialMedia: {
      instagram: "https://instagram.com/olivia.martinez.sculpture",
      twitter: "https://twitter.com/oliviamartinez",
      website: "https://oliviamartinez.art",
    },
    biography:
      "Olivia Martinez creates bold sculptural works that explore the dynamic relationship between form, space, and material. Working primarily with metal, her pieces often feature dramatic lines and precarious balances that challenge perceptions of weight and stability.\n\nMartinez's approach to sculpture is informed by her background in engineering and her interest in the physical properties of materials. Her work investigates themes of tension, equilibrium, and the intersection of natural and industrial forms.\n\nBased in Seattle, Martinez has developed innovative techniques for working with steel and other metals. Her large-scale public installations can be found in urban spaces across the United States, where they create striking dialogues with their architectural surroundings.",
    born: "1984, Mexico City, Mexico",
    nationality: "Mexican-American",
    education: "MFA in Sculpture, Rhode Island School of Design; BS in Mechanical Engineering, MIT",
    awards: "Public Art Network Award (2022), Sculpture Space Fellowship (2019)",
    exhibitions: [
      {
        title: "Forces in Balance: Solo Exhibition",
        year: "2023",
        location: "Seattle Art Museum",
      },
      {
        title: "Metal and Motion",
        year: "2022",
        location: "Museum of Contemporary Craft, Portland",
      },
      {
        title: "Structural Innovations",
        year: "2020",
        location: "Sculpture Center, New York",
      },
      {
        title: "Women in Sculpture",
        year: "2018",
        location: "National Museum of Women in the Arts, Washington DC",
      },
    ],
  },
  {
    id: "8",
    name: "James Wilson",
    specialty: "Photographer",
    location: "New York, USA",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=800&h=800&fit=crop",
    socialMedia: {
      instagram: "https://instagram.com/james.wilson.photo",
      twitter: "https://twitter.com/jameswilson",
      website: "https://jameswilson.photo",
    },
    biography:
      "James Wilson is renowned for his black and white photography that captures the poetic dimensions of urban life. His work combines documentary precision with artistic sensibility, revealing intimate moments within public spaces.\n\nWilson's photographic practice is characterized by patient observation and an intuitive sense of timing. Working primarily with traditional film cameras and silver gelatin printing processes, he maintains a connection to the craft's historical roots while addressing contemporary themes.\n\nBased in New York City, Wilson finds endless inspiration in the city's diverse neighborhoods and inhabitants. His images have been widely published and exhibited, earning recognition for their distinctive visual style and emotional resonance.",
    born: "1975, London, UK",
    nationality: "British-American",
    education: "MA in Photography, School of Visual Arts, New York",
    awards: "Leica Oskar Barnack Award (2021), ICP Infinity Award (2018)",
    exhibitions: [
      {
        title: "Street Poetry: Solo Exhibition",
        year: "2023",
        location: "International Center of Photography, New York",
      },
      {
        title: "Urban Narratives",
        year: "2022",
        location: "Tate Modern, London",
      },
      {
        title: "The Decisive Moment",
        year: "2020",
        location: "Aperture Foundation, New York",
      },
      {
        title: "Black and White in America",
        year: "2018",
        location: "Museum of the City of New York",
      },
    ],
  },
]

export const exhibitions = [
  {
    id: 1,
    title: "Modern Perspectives",
    description: "A contemporary exploration of urban landscapes through the lens of emerging photographers.",
    startDate: "2024-03-15",
    endDate: "2024-04-15",
    location: "Main Gallery",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?q=80&w=1000",
    curator: "Sarah Chen",
    featuredArtists: ["Alex Rivera", "Maya Patel", "James Wilson"],
    status: "upcoming"
  },
  {
    id: 2,
    title: "Abstract Realities",
    description: "An immersive journey through abstract art that challenges conventional perspectives.",
    startDate: "2024-02-01",
    endDate: "2024-03-01",
    location: "East Wing",
    image: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?q=80&w=1000",
    curator: "David Kim",
    featuredArtists: ["Emma Thompson", "Carlos Rodriguez", "Lisa Chang"],
    status: "current"
  },
  {
    id: 3,
    title: "Digital Frontiers",
    description: "Exploring the intersection of technology and art in the digital age.",
    startDate: "2024-01-10",
    endDate: "2024-02-10",
    location: "Digital Gallery",
    image: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?q=80&w=1000",
    curator: "Maria Garcia",
    featuredArtists: ["Tom Anderson", "Sophie Lee", "Raj Patel"],
    status: "past"
  },
  {
    id: 4,
    title: "Nature's Canvas",
    description: "A celebration of natural beauty through various artistic mediums.",
    startDate: "2024-04-20",
    endDate: "2024-05-20",
    location: "Garden Gallery",
    image: "https://images.unsplash.com/photo-1579783901586-d88db74b4fe4?q=80&w=1000",
    curator: "John Smith",
    featuredArtists: ["Anna White", "Michael Brown", "Yuki Tanaka"],
    status: "upcoming"
  },
  {
    id: 5,
    title: "Cultural Fusion",
    description: "A vibrant showcase of art that bridges different cultural traditions.",
    startDate: "2024-03-01",
    endDate: "2024-04-01",
    location: "International Wing",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?q=80&w=1000",
    curator: "Fatima Ahmed",
    featuredArtists: ["Lucas Silva", "Aisha Khan", "Marcus Johnson"],
    status: "current"
  },
  {
    id: 6,
    title: "Minimalist Expressions",
    description: "Exploring the power of simplicity in contemporary art.",
    startDate: "2023-12-01",
    endDate: "2024-01-01",
    location: "West Wing",
    image: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?q=80&w=1000",
    curator: "Peter Wong",
    featuredArtists: ["Sarah Miller", "Daniel Park", "Olivia Chen"],
    status: "past"
  }
];

export const teamMembers = [
  {
    id: "1",
    name: "Dr. Sarah Chen",
    position: "Chief Curator",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "2",
    name: "Michael Torres",
    position: "Photography Curator",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "3",
    name: "Dr. Elena Vasquez",
    position: "Contemporary Art Curator",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "4",
    name: "James Morrison",
    position: "Sculpture Curator",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "5",
    name: "Dr. Alex Chen",
    position: "Digital Arts Curator",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "6",
    name: "Maria Rodriguez",
    position: "Gallery Director",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "7",
    name: "David Park",
    position: "Education Coordinator",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "8",
    name: "Lisa Thompson",
    position: "Collections Manager",
    image: "/placeholder.svg?height=400&width=400",
  },
]
